name: Deployment from github to AWS
on:
  push:
    branches:
      - master
jobs:
  deploy:
    steps:
      - name: Checkout latest rep
        uses: actions/checkout@master
        
      - name: Generate Delpoyment Package
        run: zip -r deploy.zip * -x "**node_modules**"
        
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time
          
      - name: Deploy to EB
        uses: k89jy/simple-engineer-aws-delpyment-tutorial@master
        env:
          eb_package_s3_bucket_name: "elb-node-server"
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: simple-engineer-delpoyment-tutorial
          environment_name: Simpleengineerdelpoymenttutorial-env
          region: ap-northeast-1
          deployment_package: deploy.zip
          
